CREATE TABLE RESTRICTION_LEVEL (
    ID           BIGINT      NOT NULL AUTO_INCREMENT COMMENT 'RESTRICTION_LEVEL id',
    EMPLOYEE_ID  BIGINT      NOT NULL COMMENT '직원 번호',
    ACCESS_ROLE  BIGINT      NOT NULL COMMENT '접근 권한 레벨',
    CREATED_AT   DATETIME    NOT NULL COMMENT '권한 생성 날짜',
    EXPIRED_AT   DATETIME    NOT NULL COMMENT '권한 만료 날짜',

    PRIMARY KEY (ID)
);

ALTER TABLE RESTRICTION_LEVEL
    ADD CONSTRAINT FK_RESTRICTION_LEVEL_EMPLOYEE_ID
        FOREIGN KEY (EMPLOYEE_ID)
            REFERENCES EMPLOYEE (ID);
