CREATE TABLE EMPLOYEE (
    ID         BIGINT      NOT NULL AUTO_INCREMENT COMMENT '직원 번호',
    ENO        VARCHAR(10) NOT NULL UNIQUE COMMENT '직원 번호',
    NAME       VARCHAR(20) NOT NULL COMMENT '직원 이름',
    ENTERYEAR  INT         NOT NULL COMMENT '압사 날짜(년)',
    ENTERMONTH INT         NOT NULL COMMENT '압사 날짜(월)',
    ENTERDAY   INT         NOT NULL COMMENT '압사 날짜(일)',
    ROLE       VARCHAR(20) NOT NULL COMMENT '작책',
    SECNO      VARCHAR(10) DEFAULT NULL COMMENT '비서 번호',

    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT '직원';