version: "3.8"                                          # 파일 규격 버전
services:
  webmvc-database:
    container_name: webmvc-database                   # 컨테이너 이름
    build:                                            # 이미지 빌드
      dockerfile: Dockerfile                           # Dockerfile 경로
      context: ./database                            # Dockerfile 경로
    image: jjuuuunn/webmvc-mariadb                        # 이미지 이름
    environment: # 환경 변수
      - MARIADB_DATABASE=${DB_NAME} # 데이터베이스 이름
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD} # root 비밀번호
      - MARIADB_USER=${DB_USER} # 사용자 이름
      - MARIADB_PASSWORD=${DB_PASSWORD} # 사용자 비밀번호
    volumes:
      - ./database/mariadb.cnf:/etc/mysql/conf.d       # 설정 파일
      - ./database/init:/docker-entrypoint-initdb.d        # 초기화 스크립트
    ports:
        - "3307:3306"                                  # 호스트 포트:컨테이너 포트
