CREATE TABLE RESTRICTION_LEVEL (
    ID           BIGINT      NOT NULL AUTO_INCREMENT COMMENT 'RESTRICTION_LEVEL id',
    EMPLOYEE_ID  BIGINT      NOT NULL COMMENT '직원 번호',
    ACCESS_ROLE  VARCHAR(20) NOT NULL COMMENT '접근 권한 레벨',
    CREATED_AT   DATETIME    NOT NULL COMMENT '권한 생성 날짜',
    EXPIRED_AT   DATETIME    NOT NULL COMMENT '권한 만료 날짜',

    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='접근 제한 권한';

ALTER TABLE RESTRICTION_LEVEL
    ADD CONSTRAINT FK_RESTRICTION_LEVEL_EMPLOYEE_ID
        FOREIGN KEY (EMPLOYEE_ID)
            REFERENCES EMPLOYEE (ID);