version: "3.8"                                          # 파일 규격 버전
services:
  spring-product-manage-database:
    container_name: spring-product-manage                   # 컨테이너 이름
    build:                                            # 이미지 빌드
      dockerfile: Dockerfile                           # Dockerfile 경로
      context: ./db                            # Dockerfile 경로
    image: jjuuuunn/spring-product-manage-mariadb                        # 이미지 이름
    environment: # 환경 변수
      - MARIADB_DATABASE=product # 데이터베이스 이름
      - MARIADB_ROOT_PASSWORD=0 # root 비밀번호
      - MARIADB_USER=yang # 사용자 이름
      - MARIADB_PASSWORD=0 # 사용자 비밀번호
    volumes:
      - ./db/mariadb.cnf:/etc/mysql/conf.d       # 설정 파일
      - ./db/init:/docker-entrypoint-initdb.d        # 초기화 스크립트
    ports:
        - "3307:3306"                                  # 호스트 포트:컨테이너 포트
